name: Release

on:
  release:
    types: [published]

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Cache Go modules
      uses: actions/cache@v5
      with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go

    - name: Build
      run: go build -trimpath -ldflags="-s -w -X main.version=${{ github.event.release.tag_name }}" -o dist/devops-tools-${{ matrix.os }}-${{ matrix.arch }} -v .
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}

    - name: Add exe extension for Windows
      if: matrix.os == 'windows'
      run: mv dist/devops-tools-windows-amd64 dist/devops-tools-windows-amd64.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: devops-tools-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/devops-tools-${{ matrix.os }}-${{ matrix.arch }}*

  upload-assets:
    name: Upload Release Assets
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Upload assets to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ./artifacts/*; do
            gh release upload "${{ github.event.release.tag_name }}" "$file" --repo ${{ github.repository }}
          done

      - name: Mark release as non-prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit ${{ github.event.release.tag_name }} --prerelease=false --repo ${{ github.repository }}
        # Only mark as non-prerelease if the tag does not contain "rc"
        if: "!contains(github.event.release.tag_name, 'rc')"